[project]
name = "bm_aiohttp"
dependencies = [
    "aiohttp",
    "gunicorn",
    "requests",
    "uvloop",
]

# XXX This should be inherited from metabase.
dynamic = [
  "name",
  "version",
]

[tool.pyperformance]
# "name" is set automatically.
metabase = ".."
