[project]
name = "bm_flaskblogging"
dependencies = [
    "Flask",
    "Flask-Blogging",
    "requests",
]

# XXX This should be inherited from metabase.
dynamic = [
  "name",
  "version",
]

[tool.pyperformance]
# "name" is set automatically.
metabase = ".."
