[project]
name = "python-macrobenchmarks"
version = "1.0.0"
description = "Pyston benchmarks"
#requires-python = ">=3.8"
dependencies = ["pyperf"]
urls = {repository = "https://github.com/pyston/python-macrobenchmarks"}

[tool.pyperformance]
manifest = "benchmarks/MANIFEST"
